# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: us.gcr.io/sadc-trinity/trinity-circle-builds:1.1.1
        auth :
          username: _json_key
          password: $GCP_KEY

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache: 
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      #build 
      - run: 
          name: Build jar
          command:
            mvn package


  test:
    docker:
    # specify the version you desire here
    - image: us.gcr.io/sadc-trinity/trinity-circle-builds:1.1.1
      auth :
        username: _json_key
        password: $GCP_KEY

    steps:
      - checkout

      - run:
        name: Running unit tests
        command: 
          mvn test

  deploy:
    docker:
      # specify the version you desire here
      - image: us.gcr.io/sadc-trinity/trinity-circle-builds:1.1.1
        auth :
          username: _json_key
          password: $GCP_KEY

    steps:
      - checkout

      - run:
        name: Authenticate to GCP
        command:
          echo "$GCP_KEY" > "GCP_KEY.json";
          gcloud auth activate-service-account --key-file=GCP_KEY.json

      - run:
          name: Copy jar to api-builds bucket
          command:
            file=$(ls target/javabackend* | head -1);
            gsutil cp $file gs://api-builds


workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test
      - deploy:
          filters:
            branches:
              only: master
