# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: us.gcr.io/sadc-trinity/trinity-circle-builds:1.1.1
        auth :
          username: _json_key
          password: $GCP_KEY

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache: 
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
        
      # run tests
      - run:
        name: Running unit tests
        command: 
          mvn integration-test
      
      #build 
      - run: 
        name: Build jar
        command:
          mvn package

      #Copy json key
      - run: 
        name: Copy GCP key to a file
        command:
          cat $GCP_KEY > GCP_KEY.json
      
      #Authenticate to gcp with service account
      - run:
        name: Authenticate to GCP
        command:
          gcloud auth activate-service-account --key-file=GCP_KEY.json

